export const POS_SHORTCUTS = {
  NEW_CUSTOMER: 'F1',
  CUSTOMER_SEARCH: 'F2',
  SEARCH: 'F3',
  HOLD_SALE: 'F4',
  HELD_SALES: 'F5',
  RECEIPT_SEARCH: 'F6',
  CLEAR_CART: 'F7',
  BARCODE: 'F8',
  DAILY_REPORT: 'F9',
  PAYMENT: 'F12',
}
